# Charlieplex SPI bridge: Linux frames -> on-board LED matrix.

CONFIG_SPI=y
CONFIG_SPI_SLAVE=y
CONFIG_SPI_STM32_INTERRUPT=y
CONFIG_GPIO=y
CONFIG_PINCTRL=y

CONFIG_DISPLAY=y

CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=2048
